project:
  type: website
  output-dir: docs

website:
  title: "Hsin-Ju Li"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      - cosmo
      - brand
      - minty
    css: styles.css
    toc: true
    page-layout: full



